# Generated by Django 5.0 on 2025-01-28 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
    ]
