# Generated by Django 5.0 on 2025-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_server', '0002_userip'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserSettings',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('user_id', models.CharField(max_length=255, unique=True)),
                        ('blocked_sites', models.TextField(default='[]')),
                        ('excluded_sites', models.TextField(default='[]')),
                        ('categories', models.JSONField(default=list)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'user_settings',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
